// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzeVR_esRglJruRBanVcvwkaU42dDPDq4',
    appId: '1:872504505062:web:626a2d48006cbb2c2ac127',
    messagingSenderId: '872504505062',
    projectId: 'mica-school-app-32842',
    authDomain: 'mica-school-app-32842.firebaseapp.com',
    storageBucket: 'mica-school-app-32842.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4zKoOxYwV5MZhzHPvYuygVfkFNu_AHc',
    appId: '1:872504505062:android:b89617400ff7eeb92ac127',
    messagingSenderId: '872504505062',
    projectId: 'mica-school-app-32842',
    storageBucket: 'mica-school-app-32842.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ5s8fSTWovGOrqMIkv2rFAFEhbl8-PlI',
    appId: '1:872504505062:ios:1292364bb202f9332ac127',
    messagingSenderId: '872504505062',
    projectId: 'mica-school-app-32842',
    storageBucket: 'mica-school-app-32842.firebasestorage.app',
    iosBundleId: 'com.example.micaSchoolApp',
  );
}
