// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkj2iEs5UkFNzu1S7PistHPurQFqVe5H0',
    appId: '1:219498015860:web:b0081d1b100a28b14ef521',
    messagingSenderId: '219498015860',
    projectId: 'mica-school-project',
    authDomain: 'mica-school-project.firebaseapp.com',
    databaseURL: 'https://mica-school-project-default-rtdb.firebaseio.com',
    storageBucket: 'mica-school-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAec0CXGZts0SpfWUXuCHDRL_EyHel-muY',
    appId: '1:219498015860:android:443c62cd3dba04e54ef521',
    messagingSenderId: '219498015860',
    projectId: 'mica-school-project',
    databaseURL: 'https://mica-school-project-default-rtdb.firebaseio.com',
    storageBucket: 'mica-school-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQX2JJtL_7CfgCM7L4Fn9WquS-Y9U2l0M',
    appId: '1:219498015860:ios:9594c5fcb8a52b424ef521',
    messagingSenderId: '219498015860',
    projectId: 'mica-school-project',
    databaseURL: 'https://mica-school-project-default-rtdb.firebaseio.com',
    storageBucket: 'mica-school-project.firebasestorage.app',
    iosBundleId: 'com.example.micaSchoolApp',
  );

}